In [1]:
import numpy

array1 = numpy.arange(3)
array2 = numpy.arange(-3,3).reshape((2,3))
array3 = numpy.arange(1,7).reshape((2,3))
array4 = numpy.arange(6).reshape((3,2))
array5 = numpy.linspace(-1,1,10)

print(array1)
print()
print(array2)
print()
print(array3)
print()
print(array4)
print()
print(array5)
print()

[0 1 2]

[[-3 -2 -1]
 [ 0  1  2]]

[[1 2 3]
 [4 5 6]]

[[0 1]
 [2 3]
 [4 5]]

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]



# ユニバーサルファンクション
配列要素内のデータを一括で変換するNumpy特有の便利機能  
Python標準では、forや内包などを用いて行う操作を、メソッド呼び出しのみで済ませる事が出来る

### 要素の絶対値を取得

In [3]:
numpy.abs(array2)

array([[3, 2, 1],
       [0, 1, 2]])

In [4]:
numpy.abs(array5)

array([1.        , 0.77777778, 0.55555556, 0.33333333, 0.11111111,
       0.11111111, 0.33333333, 0.55555556, 0.77777778, 1.        ])

### 要素の三角関数値を取得

In [5]:
numpy.sin(array1)

array([0.        , 0.84147098, 0.90929743])

In [7]:
numpy.cos(array2)

array([[-0.9899925 , -0.41614684,  0.54030231],
       [ 1.        ,  0.54030231, -0.41614684]])

In [8]:
numpy.tan(array3)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

### 要素の自然対数を取得

In [10]:
numpy.log(array3)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [12]:
# 対数関数はx>0の時のみ定義されるため、負の値や0を含むとwarningが出る
numpy.log(array2)

c:\users\box16\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
c:\users\box16\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


array([[       nan,        nan,        nan],
       [      -inf, 0.        , 0.69314718]])

### 要素の常用対数を取得

In [14]:
numpy.log10(array3)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

### 要素のexpを取得

In [15]:
numpy.exp(array1)

array([1.        , 2.71828183, 7.3890561 ])

In [16]:
numpy.exp(array5)

array([0.36787944, 0.45942582, 0.57375342, 0.71653131, 0.89483932,
       1.11751907, 1.39561243, 1.742909  , 2.17662993, 2.71828183])

# ブロードキャスト
行列演算が容易に行えるシステム  

In [21]:
print(array1)
array1 + 10

[0 1 2]


array([10, 11, 12])

In [22]:
print(array2)
print()
print(array3)
array2 + array3

[[-3 -2 -1]
 [ 0  1  2]]

[[1 2 3]
 [4 5 6]]


array([[-2,  0,  2],
       [ 4,  6,  8]])

In [23]:
# 要素数が合わなくても計算できる
print(array1)
print()
print(array2)
array1 + array2

[0 1 2]

[[-3 -2 -1]
 [ 0  1  2]]


array([[-3, -1,  1],
       [ 0,  2,  4]])

In [27]:
convert_array1 = array1[:,numpy.newaxis]
print(convert_array1)
print()
print(array1)

convert_array1 + array1

[[0]
 [1]
 [2]]

[0 1 2]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [28]:
# 計算できない場合もある
convert_array1 + array2

ValueError: operands could not be broadcast together with shapes (3,1) (2,3) 

In [29]:
# 分散を求める時などに便利な、平均偏差を求める方法
array3 - numpy.mean(array3)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [30]:
array4 * 2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [31]:
array5 ** 2

array([1.        , 0.60493827, 0.30864198, 0.11111111, 0.01234568,
       0.01234568, 0.11111111, 0.30864198, 0.60493827, 1.        ])

In [32]:
array1 - array2

array([[3, 3, 3],
       [0, 0, 0]])

In [33]:
array2 * array3

array([[-3, -4, -3],
       [ 0,  5, 12]])

In [35]:
array2 / array3

array([[-3.        , -1.        , -0.33333333],
       [ 0.        ,  0.2       ,  0.33333333]])

### 行列の割り算で、分母側に0が入り得る時の回避テクニック
微小な値を加算して、0ではないが、ほぼ0というように操作する

In [36]:
array3 / array2

c:\users\box16\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[-0.33333333, -1.        , -3.        ],
       [        inf,  5.        ,  3.        ]])

In [37]:
array3 / (array2 + 1e-6)

array([[-3.33333444e-01, -1.00000050e+00, -3.00000300e+00],
       [ 4.00000000e+06,  4.99999500e+00,  2.99999850e+00]])

0で割る以外の計算は、ほぼ同じ値になり、  
0で割る計算は置き換えられて、かなり大きな値を算出するようになる(infを意味する)

### ドット積
ドット積を行う方法は2つある

In [38]:
numpy.dot(array2,array1)

array([-4,  5])

In [39]:
# Python3.5以降で可能な方法
array2 @ array1

array([-4,  5])

In [40]:
# ドット積は行列演算の制約を受けるため、行列の形が重要となる
array1 @ array2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

ドット演算は  
  
$N\times M \cdot M\times N = N\times N$行列  
  
となる

In [42]:
print(array1.shape)
print(array2.shape)
print(array3.shape)
print(array4.shape)
print(array5.shape)

(3,)
(2, 3)
(2, 3)
(3, 2)
(10,)


この場合可能なドット積の組み合わせは  
2-1  
3-1  
2-4  
3-4  
4-2  
4-3

In [43]:
array2 @ array1

array([-4,  5])

In [44]:
array3 @ array1

array([ 8, 17])

In [45]:
array2 @ array4

array([[ -8, -14],
       [ 10,  13]])

In [46]:
array3 @ array4

array([[16, 22],
       [34, 49]])

In [47]:
array4 @ array2

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

In [48]:
array4 @ array3

array([[ 4,  5,  6],
       [14, 19, 24],
       [24, 33, 42]])

### 判定・論理値
配列とスカラーを演算子で比較すると、それぞれの要素との結果が、行列の形で返ってくる

In [49]:
array1 > 1

array([False, False,  True])

In [51]:
array2 > 1

array([[False, False, False],
       [False, False,  True]])

In [53]:
print(array3)
array3 % 2 == 0

[[1 2 3]
 [4 5 6]]


array([[False,  True, False],
       [ True, False,  True]])

In [54]:
# nonzeroを用いる事でtrueの数を数えることも出来る
numpy.count_nonzero(array3 % 2 == 0)

3

In [55]:
# もしくはFalse=0 True=1であるため、全要素の足し算でも同じ結果が得られる
numpy.sum(array3 % 2 == 0)

3

In [56]:
# 判定結果に一つでもTrueがあるか
numpy.any(array3 % 2 == 0)

True

In [57]:
# 判定結果が全てTrueであるか
numpy.all(array3 % 2 == 0)

False

In [58]:
# リスト内包のように、条件に一致するものだけで行列を構成する
array3[array3 % 2 == 0]

array([2, 4, 6])

In [60]:
# 行列同士の比較
# 形がそろっていないと行えない演算
array2 == array3

array([[False, False, False],
       [False, False, False]])

In [62]:
array1 == array2

array([[False, False, False],
       [ True,  True,  True]])

In [64]:
print((array2 == array3))
print()
print((array1 == array2))
print()
print((array2 == array3) | (array1 == array2))

[[False False False]
 [False False False]]

[[False False False]
 [ True  True  True]]

[[False False False]
 [ True  True  True]]


In [65]:
array2[(array2 == array3) | (array1 == array2)]

array([0, 1, 2])

allcloseを用いれば、指定した誤差の範囲内か(close=近いか)を判定できる

In [66]:
numpy.allclose(array2,array3)

False

In [67]:
# atolで誤差範囲を指定できる
numpy.allclose(array2,array3,atol=10)

True

# Numpyの関数とメソッド

In [69]:
# 要素の合計値を求める
numpy.sum(array2)

-3

In [72]:
# データ
print(array2)
print()
# 平均偏差
print(array2 - numpy.mean(array2))
print()
# 平均偏差平方
print((array2 - numpy.mean(array2))**2)
print()
# 平均偏差平方和
print(numpy.sum((array2 - numpy.mean(array2))**2))
print()

[[-3 -2 -1]
 [ 0  1  2]]

[[-2.5 -1.5 -0.5]
 [ 0.5  1.5  2.5]]

[[6.25 2.25 0.25]
 [0.25 2.25 6.25]]

17.5



In [73]:
#sumには二つ方法がある
numpy.sum(array2)

-3

In [74]:
array2.sum()

-3